### ISSUE TITLE
The number of epoch for SOP dataset

### ISSUE THREAD

**Issue by darkpromise98** [ExplainableML/NonIsotropicProxyDML#5]
A great work for metric learning. I notice the number of epoch for SOP dataset is very large (300 epoch) during training. Why it's different with CUB and CARS datasets (about 100 epoch) ? Since SOP is large datasets, it will lead to long training time. Or only with large training time, the method  is effective？

**Comment by Confusezius** [comment]
Oh that's not required, you can easily do with 100 epochs on SOP as well :).
